# Generated by Django 4.2.7 on 2025-12-02 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='checkout_request_id',
            field=models.CharField(blank=True, help_text='M-Pesa Checkout Request ID', max_length=200),
        ),
        migrations.AddField(
            model_name='payment',
            name='merchant_request_id',
            field=models.CharField(blank=True, help_text='M-Pesa Merchant Request ID', max_length=200),
        ),
    ]
